# Generated by Django 5.1.7 on 2025-03-09 15:40

from django.db import migrations

def populate_plan_choice(apps, schema_editor):
    PlanChoice = apps.get_model('client','PlanChoices')
    PlanChoice.objects.create(
        plan = 'ST',
        name = 'Standard',
        cost = '3.00',
        is_active = True,
        description1 = 'Get access to standard articles and reports',
        description2 = 'Limited access',
        external_plan_id = 'P-96N03243YA686315WM7AY6UQ',
        external_api_url = 'https://www.paypal.com/sdk/js?client-id=Abl13b4l626eZpYnYtOiswfYw00KdwlbiQlwT9F1VD2oPsQisFrylTzrrD5K5uzYG0jDCJHi61yQapcz&vault=true&intent=subscription',
        external_style_json = """{
            "shape": "pill",
            "color": "silver",
            "layout": "vertical",
            "label": "subscribe"
        }"""
    )   
   

    PlanChoice.objects.create(
        plan = 'PR',
        name = 'Premium',
        cost = '9.99',
        is_active = True,
        description1 = 'Get access to premium articles and reports',
        description2 = 'Unlimited access',
        external_plan_id = 'P-0M954387DT521152XM66KAHY',
        external_api_url = 'https://www.paypal.com/sdk/js?vault=true&intent=subscription',
        external_style_json = """{
            "shape": "pill",
            "color": "gold",
            "layout": "vertical",
            "label": "subscribe"
        }"""
    )



class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_planchoices_alter_subscription_const'),
    ]

    operations = [
          migrations.RunPython(populate_plan_choice),
    ]
